import Head from "next/head";
import Image from "next/image";
import styles from "../styles/contact.module.scss";

// Components
import Nav from "../components/nav";
import Footer from "../components/footer";
import Form from "../components/form";

export default function Contact() {
    return (
        <div>
            <Nav />

            <Head>
                <title>Contact Chul-eun Lee</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="author" href="https://charlieberens.org" />
            </Head>

            <main className={`${styles.main} mc`}>
                <div>
                    <h1 className={styles.title}>Contact Chul-eun Lee</h1>
                    <Form />
                </div>
            </main>

            <Footer />
        </div>
    );
}
